apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ips.rocdu.top
spec:
  group: rocdu.top
  version: v1
  scope: Namespaced
  names:
    plural: ips
    singular: ip
    kind: Ip
    shortNames:
      - ip

---

apiVersion: rocdu.top/v1
kind: Ip
metadata:
  name: 1.2.3.4