/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/du2016/code-generator/pkg/apis/ip/v1"
	scheme "github.com/du2016/code-generator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// IpsGetter has a method to return a IpInterface.
// A group's client should implement this interface.
type IpsGetter interface {
	Ips(namespace string) IpInterface
}

// IpInterface has methods to work with Ip resources.
type IpInterface interface {
	Create(*v1.Ip) (*v1.Ip, error)
	Update(*v1.Ip) (*v1.Ip, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Ip, error)
	List(opts metav1.ListOptions) (*v1.IpList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Ip, err error)
	IpExpansion
}

// ips implements IpInterface
type ips struct {
	client rest.Interface
	ns     string
}

// newIps returns a Ips
func newIps(c *RocduV1Client, namespace string) *ips {
	return &ips{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ip, and returns the corresponding ip object, and an error if there is any.
func (c *ips) Get(name string, options metav1.GetOptions) (result *v1.Ip, err error) {
	result = &v1.Ip{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ips").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Ips that match those selectors.
func (c *ips) List(opts metav1.ListOptions) (result *v1.IpList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.IpList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ips.
func (c *ips) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a ip and creates it.  Returns the server's representation of the ip, and an error, if there is any.
func (c *ips) Create(ip *v1.Ip) (result *v1.Ip, err error) {
	result = &v1.Ip{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ips").
		Body(ip).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ip and updates it. Returns the server's representation of the ip, and an error, if there is any.
func (c *ips) Update(ip *v1.Ip) (result *v1.Ip, err error) {
	result = &v1.Ip{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ips").
		Name(ip.Name).
		Body(ip).
		Do().
		Into(result)
	return
}

// Delete takes name of the ip and deletes it. Returns an error if one occurs.
func (c *ips) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ips").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ips) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ips").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ip.
func (c *ips) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Ip, err error) {
	result = &v1.Ip{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ips").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
