/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	netv1 "github.com/du2016/code-generator/pkg/apis/net/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNets implements NetInterface
type FakeNets struct {
	Fake *FakeNetV1
	ns   string
}

var netsResource = schema.GroupVersionResource{Group: "net.rocdu.top", Version: "v1", Resource: "nets"}

var netsKind = schema.GroupVersionKind{Group: "net.rocdu.top", Version: "v1", Kind: "Net"}

// Get takes name of the net, and returns the corresponding net object, and an error if there is any.
func (c *FakeNets) Get(name string, options v1.GetOptions) (result *netv1.Net, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(netsResource, c.ns, name), &netv1.Net{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netv1.Net), err
}

// List takes label and field selectors, and returns the list of Nets that match those selectors.
func (c *FakeNets) List(opts v1.ListOptions) (result *netv1.NetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(netsResource, netsKind, c.ns, opts), &netv1.NetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &netv1.NetList{ListMeta: obj.(*netv1.NetList).ListMeta}
	for _, item := range obj.(*netv1.NetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nets.
func (c *FakeNets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(netsResource, c.ns, opts))

}

// Create takes the representation of a net and creates it.  Returns the server's representation of the net, and an error, if there is any.
func (c *FakeNets) Create(net *netv1.Net) (result *netv1.Net, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(netsResource, c.ns, net), &netv1.Net{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netv1.Net), err
}

// Update takes the representation of a net and updates it. Returns the server's representation of the net, and an error, if there is any.
func (c *FakeNets) Update(net *netv1.Net) (result *netv1.Net, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(netsResource, c.ns, net), &netv1.Net{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netv1.Net), err
}

// Delete takes name of the net and deletes it. Returns an error if one occurs.
func (c *FakeNets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(netsResource, c.ns, name), &netv1.Net{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(netsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &netv1.NetList{})
	return err
}

// Patch applies the patch and returns the patched net.
func (c *FakeNets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *netv1.Net, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(netsResource, c.ns, name, pt, data, subresources...), &netv1.Net{})

	if obj == nil {
		return nil, err
	}
	return obj.(*netv1.Net), err
}
